# Generated by Django 4.1.6 on 2023-07-31 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='family',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
