# Generated by Django 4.2.3 on 2023-07-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Pome fruits', 'Pome fruits'), ('Stone fruits', 'Stone fruits'), ('Multiple ftuits', 'Multiple ftuits'), ('Nuts ', 'Nuts '), ('Small fruits', 'Small fruits')], default='Pome fruits', max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='fruits/')),
                ('available', models.BooleanField(default=False)),
                ('Capacity', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
